"use strict";

CourseProgress.visit(8);

document.querySelectorAll(".readiness-choices button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".readiness-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#readinessFeedback").textContent=correct?"Correct. Each stage consumes state produced by the earlier stages, and clearing prevents stale gradients from entering an independent batch.":"Not quite. Revisit Lesson 7's gradient-state simulator before continuing.";}));

const dtypeBytes={float16:2,bfloat16:2,float32:4,float64:8,int64:8};
function formatBytes(bytes){return bytes<1024?`${bytes} bytes`:bytes<1024**2?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1024**2).toFixed(2)} MiB`;}
function updateTensor(){const batch=Number(document.querySelector("#tensorBatch").value),width=Number(document.querySelector("#tensorWidth").value),dtype=document.querySelector("#tensorDtype").value,device=document.querySelector("#tensorDevice").value,wantsGradient=document.querySelector("#tensorGrad").checked,elements=batch*width,integer=dtype.startsWith("int");document.querySelector("#tensorBatchValue").value=batch;document.querySelector("#tensorWidthValue").value=width;document.querySelector("#tensorShape").textContent=`(${batch}, ${width})`;document.querySelector("#tensorElements").textContent=elements.toLocaleString();document.querySelector("#tensorMemory").textContent=formatBytes(elements*dtypeBytes[dtype]);document.querySelector("#tensorDeviceValue").textContent=device==="cpu"?"CPU":"Accelerator";document.querySelector("#tensorGradValue").textContent=wantsGradient?(integer?"Invalid for int64":"Tracked"):"Not tracked";document.querySelector("#tensorMeaning").textContent=integer&&wantsGradient?"This combination is invalid for ordinary autograd: a discrete integer tensor cannot represent infinitesimal changes. Keep indices and labels integer, while learned parameters and differentiable values use floating point.":dtype==="float16"||dtype==="bfloat16"?"Lower precision halves value storage relative to float32. Actual training memory also includes gradients, optimizer state, saved activations, and temporary workspaces.":`This tensor stores ${elements.toLocaleString()} ${dtype} values on the ${device==="cpu"?"CPU":"selected accelerator"}. Shape describes organization; dtype and device must be compatible with connected operations.`;}
document.querySelectorAll("#tensorBatch, #tensorWidth, #tensorDtype, #tensorDevice, #tensorGrad").forEach(input=>input.addEventListener("input",updateTensor));

function updateAutograd(){const tracking={x:document.querySelector("#trackX").checked,w:document.querySelector("#trackW").checked,b:document.querySelector("#trackB").checked},disabled=document.querySelector("#noGradMode").checked,recorded=!disabled&&Object.values(tracking).some(Boolean),nodes=[{name:"x",detail:"2",tracked:tracking.x},{name:"w",detail:"3",tracked:tracking.w},{name:"multiply",detail:"m = 6",tracked:recorded},{name:"b",detail:"1",tracked:tracking.b},{name:"add",detail:"p = 7",tracked:recorded},{name:"square",detail:"y = 49",tracked:recorded}];document.querySelector("#autogradGraph").innerHTML=nodes.map((node,index)=>`${index?'<span class="autograd-arrow">→</span>':""}<article class="autograd-node ${disabled?"blocked":node.tracked?"tracked":""}"><small>${node.name}</small><strong>${node.detail}</strong><span>${disabled?"not recorded":node.tracked?"tracked":"constant"}</span></article>`).join("");const gradients=[];if(recorded){if(tracking.x)gradients.push("∂y/∂x = 42");if(tracking.w)gradients.push("∂y/∂w = 28");if(tracking.b)gradients.push("∂y/∂b = 14");}document.querySelector("#autogradResult").textContent="y = 49";document.querySelector("#graphRecorded").textContent=recorded?"Yes":"No";document.querySelector("#availableGradients").textContent=gradients.length?gradients.join(" · "):"None";document.querySelector("#autogradMeaning").textContent=disabled?"Gradient recording is disabled. The forward result still exists, but no backward graph or leaf gradients are available.":recorded?"Operations depending on at least one tracked leaf form a backward graph. Backward calculates gradients only for leaves marked for tracking.":"No leaf requests gradients, so recording this graph would provide no parameter gradient and is unnecessary.";}
document.querySelectorAll("#trackX, #trackW, #trackB, #noGradMode").forEach(input=>input.addEventListener("change",updateAutograd));

const modules=[
  {id:"model",label:"DeliveryRiskNetwork",className:"",params:"All nested parameters",output:"(batch, 3)",meaning:"The root module owns the registered component tree. Recursive operations discover all three dense layers."},
  {id:"dense1",label:"Dense 1 + ReLU",className:"child",params:"W (10, 64), b (64) · 704",output:"(batch, 64)",meaning:"The activation has no learned parameter here; the dense transformation owns the registered weight and bias."},
  {id:"dense2",label:"Dense 2 + ReLU",className:"child",params:"W (64, 16), b (16) · 1,040",output:"(batch, 16)",meaning:"Nested registration lets device moves, mode changes, state collection, and optimizer discovery reach this layer."},
  {id:"head",label:"Output head",className:"child",params:"W (16, 3), b (3) · 51",output:"(batch, 3)",meaning:"The output head emits three logits. The loss interprets them according to the multiclass target contract."}
];let selectedModule="model";
function renderModules(){document.querySelector("#moduleTree").innerHTML=modules.map(module=>`<button class="${module.className} ${selectedModule===module.id?"active":""}" data-module="${module.id}">${module.label}</button>`).join("");const module=modules.find(item=>item.id===selectedModule);document.querySelector("#selectedModule").textContent=module.label;document.querySelector("#selectedParameters").textContent=module.params;document.querySelector("#selectedOutput").textContent=module.output;document.querySelector("#moduleMeaning").textContent=module.meaning;document.querySelectorAll(".module-tree button").forEach(button=>button.addEventListener("click",()=>{selectedModule=button.dataset.module;renderModules();}));}

const stageNames=["Clear","Forward","Loss","Backward","Step"];let loopStage=0,loopWeight=0,loopPrediction=null,loopLoss=null,loopGradient=5;
function renderLoop(){document.querySelector("#loopStages").innerHTML=stageNames.map((name,index)=>`<div class="loop-stage ${index<loopStage?"complete":""} ${index===loopStage&&loopStage<5?"active":""}">${index+1}. ${name}</div>`).join("");document.querySelector("#loopWeight").textContent=loopWeight.toFixed(2);document.querySelector("#loopPrediction").textContent=loopPrediction===null?"—":loopPrediction.toFixed(2);document.querySelector("#loopLoss").textContent=loopLoss===null?"—":loopLoss.toFixed(2);document.querySelector("#loopGradient").textContent=loopGradient===null?"—":loopGradient.toFixed(2);const button=document.querySelector("#nextLoopStage"),messages=["The buffer begins with stale value 5 from a prior batch. Clear it before calculating this batch.","Gradient state is clear. The forward pass can now use the current parameter.","The prediction exists; calculate its scalar loss against target 4.","Loss exists; backward can now calculate the parameter gradient.","The gradient buffer is ready; the optimizer can update the parameter.","The step changed the parameter but did not clear the buffer. Start another batch and clear it explicitly."];document.querySelector("#loopMeaning").textContent=messages[loopStage];button.textContent=loopStage<5?stageNames[loopStage]:"Start next batch";}
document.querySelector("#nextLoopStage").addEventListener("click",()=>{if(loopStage===0){loopGradient=0;loopStage=1;}else if(loopStage===1){loopPrediction=loopWeight;loopStage=2;}else if(loopStage===2){loopLoss=(loopPrediction-4)**2;loopStage=3;}else if(loopStage===3){loopGradient=2*(loopPrediction-4);loopStage=4;}else if(loopStage===4){loopWeight-=.1*loopGradient;loopStage=5;}else{loopStage=0;loopPrediction=null;loopLoss=null;}renderLoop();});document.querySelector("#resetLoop").addEventListener("click",()=>{loopStage=0;loopWeight=0;loopPrediction=null;loopLoss=null;loopGradient=5;renderLoop();});

let executionMode="train",modeRun=0,modeHistory=[];const masks=[[1,0,1,0],[0,1,1,0],[1,1,0,0],[0,1,0,1],[1,0,0,1]];
function runMode(){const output=executionMode==="eval"?[2,2,2,2]:masks[modeRun%masks.length].map(value=>value*4);modeRun++;modeHistory.unshift(output);modeHistory=modeHistory.slice(0,5);renderMode();}
function renderMode(){document.querySelector("#modeOutputs").innerHTML=modeHistory.map((output,index)=>`<div class="mode-output"><small>PASS ${modeHistory.length-index}</small><strong>[${output.join(", ")}]</strong></div>`).join("")||'<div class="mode-output"><small>NO PASS YET</small><strong>Run the input</strong></div>';document.querySelector("#modeMeaning").textContent=executionMode==="train"?"Training mode samples a dropout mask. Surviving values are rescaled so their expected magnitude remains consistent, but individual passes differ.":"Evaluation mode disables dropout, so the unchanged input and parameters produce the same output every pass. This mode switch still does not disable autograd by itself.";}
document.querySelectorAll(".mode-buttons button").forEach(button=>button.addEventListener("click",()=>{executionMode=button.dataset.mode;modeRun=0;modeHistory=[];document.querySelectorAll(".mode-buttons button").forEach(item=>item.classList.toggle("active",item===button));renderMode();}));document.querySelector("#runModePass").addEventListener("click",runMode);

const checkpointPlans={
  inference:{meaning:"Inference needs the exact model behavior and input/output contract, but not optimizer history.",items:[["Model state","Parameters and persistent buffers","required"],["Architecture/config","Reconstruct matching modules","required"],["Preprocessing and labels","Interpret inputs and outputs","required"],["Optimizer state","Not needed for inference","optional"],["Version and evaluation","Provenance and release evidence","required"]]},
  resume:{meaning:"Faithful continuation needs update history and progress state in addition to model weights.",items:[["Model state","Parameters and persistent buffers","required"],["Optimizer and scheduler","Momentum, averages, schedule","required"],["Progress state","Epoch, step, best metric","required"],["Random/scaler state","Improve trajectory continuity","required"],["Configuration and data identity","Reconstruct the run","required"]]},
  reproduce:{meaning:"Reproduction requires immutable identity for code, data, configuration, environment, and raw evaluation—not merely a restorable model.",items:[["Training checkpoint","Model, optimizer, progress","required"],["Code and dependencies","Exact version identity","required"],["Data and split identity","Samples and boundaries","required"],["Configuration and seeds","All chosen settings","required"],["Metrics and artifacts","Evidence for comparison","required"]]}
};let checkpointGoal="inference";
function renderCheckpoint(){const plan=checkpointPlans[checkpointGoal];document.querySelector("#checkpointItems").innerHTML=plan.items.map(item=>`<article class="checkpoint-item ${item[2]}"><strong>${item[0]}</strong><small>${item[1]}</small></article>`).join("");document.querySelector("#checkpointMeaning").textContent=plan.meaning;}
document.querySelectorAll(".checkpoint-buttons button").forEach(button=>button.addEventListener("click",()=>{checkpointGoal=button.dataset.goal;document.querySelectorAll(".checkpoint-buttons button").forEach(item=>item.classList.toggle("active",item===button));renderCheckpoint();}));

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — you can explain the runtime state.":"Not quite. Revisit the related interaction and try again.";})));
function completionState(){const done=CourseProgress.isComplete(8);document.querySelector("#completeLesson").textContent=done?"Lesson 8 completed ✓":"Mark Lesson 8 complete";document.querySelector("#completionStatus").textContent=done?"Your framework execution contract is ready for future implementation after Engineering Lab A.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(8);completionState();});window.addEventListener("course-progress",completionState);

updateTensor();updateAutograd();renderModules();renderLoop();renderMode();renderCheckpoint();completionState();
