"use strict";
CourseProgress.visit(2);

const objectData={scalar:{rank:"0",shape:"()",values:[7],meaning:"One value, such as a loss score.",axes:["No axes: this is one value"]},vector:{rank:"1",shape:"(5,)",values:[2,-1,4,0,3],meaning:"One example described by five ordered features.",axes:["Axis 0: 5 features"]},matrix:{rank:"2",shape:"(3, 4)",values:[1,2,3,4,5,6,7,8,9,10,11,12],meaning:"Three examples, each described by four features.",axes:["Axis 0: 3 examples","Axis 1: 4 features per example"]},tensor:{rank:"3",shape:"(2, 3, 4)",values:Array.from({length:24},(_,i)=>i+1),meaning:"Two sequences, each with three token positions; every token position has four numeric features.",axes:["Axis 0: 2 sequences","Axis 1: 3 token positions per sequence","Axis 2: 4 features per token"]}};
function renderTensorLayers(values){return `<div class="tensor-layers">${[0,1].map(sequence=>`<section class="tensor-layer"><strong>Sequence ${sequence+1}</strong><small>one item on axis 0</small><div class="layer-grid">${values.slice(sequence*12,sequence*12+12).map((value,index)=>`<span title="Sequence ${sequence+1}, token ${Math.floor(index/4)+1}, feature ${(index%4)+1}">${value}</span>`).join("")}</div><div class="layer-labels"><span>3 rows = token positions</span><span>4 columns = features</span></div></section>`).join("")}</div>`;}
function showObject(name){const item=objectData[name],visual=document.querySelector("#objectVisual");visual.className=`number-grid ${name}`;visual.innerHTML=name==="tensor"?renderTensorLayers(item.values):item.values.map(value=>`<span>${value}</span>`).join("");document.querySelector("#objectRank").textContent=item.rank;document.querySelector("#objectShape").textContent=item.shape;document.querySelector("#objectMeaning").textContent=item.meaning;document.querySelector("#objectAxisKey").innerHTML=item.axes.map(axis=>{const [label,...meaning]=axis.split(":");return `<span><b>${label}</b>${meaning.length?` ${meaning.join(":")}`:""}</span>`;}).join("");document.querySelectorAll(".object-tabs button").forEach(button=>button.classList.toggle("active",button.dataset.object===name));}
document.querySelectorAll(".object-tabs button").forEach(button=>button.addEventListener("click",()=>showObject(button.dataset.object)));
document.querySelectorAll(".shape-choices button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".shape-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#shapeFeedback").textContent=correct?"Correct. Axis 0 counts sequences, axis 1 counts token positions, and axis 2 stores the vector at each position.":"Not quite. Shape entries are ordered: batch, then token positions, then values per token.";}));

let vectorMode="add";function updateVector(){const scale=Number(document.querySelector("#vectorScale").value),a=[1,2,3].map(x=>x*scale),b=[4,-1,2];document.querySelector("#vectorScaleValue").value=scale;document.querySelector("#vectorA").textContent=`[${a.join(", ")}]`;if(vectorMode==="add"){document.querySelector("#vectorOperator").textContent="+";document.querySelector("#vectorResult").textContent=`[${a.map((x,i)=>x+b[i]).join(", ")}]`;document.querySelector("#vectorExplanation").textContent="Each result position uses the values at the same position in A and B.";}else{document.querySelector("#vectorOperator").textContent="·";document.querySelector("#vectorResult").textContent=a.reduce((sum,x,i)=>sum+x*b[i],0);document.querySelector("#vectorExplanation").textContent="The dot product multiplies corresponding positions and adds them, producing one scalar.";}document.querySelector("#vectorOperation").textContent=vectorMode==="add"?"Show A · B":"Show A + B";}
document.querySelector("#vectorScale").addEventListener("input",updateVector);document.querySelector("#vectorOperation").addEventListener("click",()=>{vectorMode=vectorMode==="add"?"dot":"add";updateVector();});

function updateMagnitude(){const x=Number(document.querySelector("#magX").value),y=Number(document.querySelector("#magY").value),sum=x*x+y*y,mag=Math.sqrt(sum);document.querySelector("#magXValue").value=x;document.querySelector("#magYValue").value=y;document.querySelector("#magSquares").textContent=`${x*x} + ${y*y} = ${sum}`;document.querySelector("#magResult").textContent=mag.toFixed(2);const canvas=document.querySelector("#magnitudeChart"),c=canvas.getContext("2d"),cx=canvas.width/2,cy=canvas.height/2,scale=12;c.clearRect(0,0,canvas.width,canvas.height);c.strokeStyle="#dbe3ec";c.beginPath();c.moveTo(20,cy);c.lineTo(canvas.width-20,cy);c.moveTo(cx,20);c.lineTo(cx,canvas.height-20);c.stroke();c.strokeStyle="#2864dc";c.lineWidth=4;c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+x*scale,cy-y*scale);c.stroke();c.fillStyle="#d64b59";c.beginPath();c.arc(cx+x*scale,cy-y*scale,6,0,Math.PI*2);c.fill();}
document.querySelector("#magX").addEventListener("input",updateMagnitude);document.querySelector("#magY").addEventListener("input",updateMagnitude);

const dotA=[1,2,3],dotB=[4,-1,2];function updateDot(){const host=document.querySelector("#dotControls");host.innerHTML="";dotB.forEach((value,index)=>{const label=document.createElement("label");label.innerHTML=`B${index+1} <output>${value}</output><input type="range" min="-5" max="5" step="1" value="${value}">`;label.querySelector("input").addEventListener("input",event=>{dotB[index]=Number(event.target.value);updateDot();});host.appendChild(label);});const products=dotA.map((value,index)=>value*dotB[index]),score=products.reduce((a,b)=>a+b,0);document.querySelector("#dotExpansion").textContent=`(1 × ${dotB[0]}) + (2 × ${dotB[1]}) + (3 × ${dotB[2]}) = ${score}`;document.querySelector("#dotInterpretation").textContent=score>0?`The score is positive (${score}); positive alignments outweigh negative ones.`:score<0?`The score is negative (${score}); opposing components dominate.`:"The positive and negative contributions cancel exactly.";}

function updateShape(){const lr=+document.querySelector("#leftRows").value,lc=+document.querySelector("#leftCols").value,rr=+document.querySelector("#rightRows").value,rc=+document.querySelector("#rightCols").value,result=document.querySelector("#shapeResult");if(lc===rr){result.className="shape-result";result.textContent=`Valid: (${lr}, ${lc}) × (${rr}, ${rc}) → (${lr}, ${rc}). The matching inner dimension ${lc} is consumed.`;}else{result.className="shape-result invalid";result.textContent=`Invalid: the left rows contain ${lc} values, but right columns contain ${rr}. The inner dimensions must match.`;}}
["leftRows","leftCols","rightRows","rightCols"].forEach(id=>document.querySelector(`#${id}`).addEventListener("input",updateShape));

const A=[[1,2,3],[4,5,6]],B=[[1,2],[0,1],[-1,3]];function renderMatrix(host,data,result=false){host.style.setProperty("--columns",data[0].length);host.innerHTML="";data.forEach((row,r)=>row.forEach((value,c)=>{const element=document.createElement(result?"button":"span");element.textContent=value;if(result)element.addEventListener("click",()=>explainCell(r,c,element));host.appendChild(element);}));}
const C=A.map(row=>B[0].map((_,c)=>row.reduce((sum,value,k)=>sum+value*B[k][c],0)));function explainCell(r,c,element){document.querySelectorAll(".result-matrix button").forEach(button=>button.classList.remove("selected"));element.classList.add("selected");const terms=A[r].map((value,k)=>`${value} × ${B[k][c]}`);document.querySelector("#cellExplanation").textContent=`Row ${r+1} · column ${c+1}: ${terms.join(" + ")} = ${C[r][c]}.`;}

let transposed=false;const transposeBase=[[1,2,3],[4,5,6]];function renderTranspose(){const data=transposed?transposeBase[0].map((_,c)=>transposeBase.map(row=>row[c])):transposeBase;renderMatrix(document.querySelector("#transposeMatrix"),data);document.querySelector("#transposeShape").textContent=`Shape: (${data.length}, ${data[0].length}). Rows became columns; the values did not change.`;document.querySelector("#transposeButton").textContent=transposed?"Restore original":"Transpose matrix";}
document.querySelector("#transposeButton").addEventListener("click",()=>{transposed=!transposed;renderTranspose();});

const batch=[[2,0,-1],[1,3,0],[-2,1,2],[0,-1,1]],bias=[.5,-1,2],broadcasted=batch.map(row=>row.map((value,c)=>value+bias[c]));renderMatrix(document.querySelector("#broadcastBatch"),batch);renderMatrix(document.querySelector("#broadcastBias"),[bias]);renderMatrix(document.querySelector("#broadcastResult"),batch);let applied=false;document.querySelector("#animateBroadcast").addEventListener("click",()=>{applied=!applied;renderMatrix(document.querySelector("#broadcastResult"),applied?broadcasted:batch);document.querySelector("#animateBroadcast").textContent=applied?"Remove bias":"Apply bias";document.querySelector("#broadcastExplanation").textContent=applied?"Every customer row received the same category adjustments: +0.5 in column 1, −1 in column 2, and +2 in column 3. The customer axis was preserved.":"The output is reset. Apply the bias to reuse the three category adjustments across all four customer rows.";});

function updateEmbedding(){const degrees=+document.querySelector("#embeddingAngle").value,length=+document.querySelector("#embeddingLength").value,angle=degrees*Math.PI/180,a=[1,0],b=[Math.cos(angle)*length,Math.sin(angle)*length],dot=b[0],cos=Math.cos(angle),distance=Math.hypot(a[0]-b[0],a[1]-b[1]);document.querySelector("#angleValue").value=`${degrees}°`;document.querySelector("#lengthValue").value=length.toFixed(1);document.querySelector("#cosineMetric").textContent=cos.toFixed(3);document.querySelector("#dotMetric").textContent=dot.toFixed(3);document.querySelector("#distanceMetric").textContent=distance.toFixed(3);const canvas=document.querySelector("#embeddingChart"),c=canvas.getContext("2d"),cx=canvas.width/2,cy=canvas.height/2,scale=90;c.clearRect(0,0,canvas.width,canvas.height);c.strokeStyle="#dbe3ec";c.beginPath();c.moveTo(20,cy);c.lineTo(canvas.width-20,cy);c.moveTo(cx,20);c.lineTo(cx,canvas.height-20);c.stroke();function arrow(x,y,color,label){c.strokeStyle=color;c.fillStyle=color;c.lineWidth=4;c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+x*scale,cy-y*scale);c.stroke();c.font="bold 14px system-ui";c.fillText(label,cx+x*scale+8,cy-y*scale);}arrow(1,0,"#2864dc","A");arrow(b[0],b[1],"#d64b59","B");document.querySelector("#embeddingExplanation").textContent=degrees<20?"The vectors point in nearly the same direction, so cosine similarity is high.":degrees>160?"The vectors point in nearly opposite directions, so cosine similarity approaches −1.":"Changing length affects dot product and distance, while cosine similarity depends only on the angle.";}
document.querySelector("#embeddingAngle").addEventListener("input",updateEmbedding);document.querySelector("#embeddingLength").addEventListener("input",updateEmbedding);

function updateTransformer(){const b=+document.querySelector("#batchSize").value,s=+document.querySelector("#sequenceLength").value,h=+document.querySelector("#hiddenSize").value;document.querySelector("#transformerShape").textContent=`(${b.toLocaleString()}, ${s.toLocaleString()}, ${h.toLocaleString()})`;document.querySelector("#transformerMeaning").textContent=`${b.toLocaleString()} sequences × ${s.toLocaleString()} token positions × ${h.toLocaleString()} values per token = ${(b*s*h).toLocaleString()} numeric activations.`;}
["batchSize","sequenceLength","hiddenSize"].forEach(id=>document.querySelector(`#${id}`).addEventListener("input",updateTransformer));

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — you can explain the mechanism.":"Not quite. Revisit the related interaction and try again.";})));
function completionState(){const done=CourseProgress.isComplete(2);document.querySelector("#completeLesson").textContent=done?"Lesson 2 completed ✓":"Mark Lesson 2 complete";document.querySelector("#completionStatus").textContent=done?"Your course dashboard has been updated.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(2);completionState();});window.addEventListener("course-progress",completionState);

showObject("matrix");updateVector();updateMagnitude();updateDot();updateShape();renderMatrix(document.querySelector("#matrixA"),A);renderMatrix(document.querySelector("#matrixB"),B);renderMatrix(document.querySelector("#matrixC"),C,true);renderTranspose();updateEmbedding();updateTransformer();completionState();
