"use strict";

CourseProgress.visit(7);

const fmt=value=>Number(value).toFixed(2).replace("-","−");
document.querySelectorAll(".readiness-choices button").forEach(button=>button.addEventListener("click",()=>{
  document.querySelectorAll(".readiness-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#readinessFeedback").textContent=correct?"Correct. A positive gradient means increasing the weight increases loss locally, so gradient descent subtracts from the weight.":"Not quite. Gradient descent moves opposite the gradient because the gradient points locally uphill.";
}));

let traceStep=0;
function graphValues(){const x=Number(document.querySelector("#graphX").value),w=Number(document.querySelector("#graphW").value),b=Number(document.querySelector("#graphB").value),m=x*w,p=m+b,y=p**2,gp=2*p,gm=gp;return{x,w,b,m,p,y,gy:1,gp,gm,gb:gp,gx:gm*w,gw:gm*x};}
const traceSteps=[
  {title:"Ready for the backward pass",explanation:"The forward pass has stored every value. Gradients are still unknown.",calculation:"Forward: m = xw, p = m + b, y = p²"},
  {title:"1. Seed the scalar loss",explanation:"A value changes one-for-one with itself, so the loss gradient starts at 1.",calculation:"∂y/∂y = 1"},
  {title:"2. Backpropagate through square",explanation:"The square operation receives upstream gradient 1. Its local derivative is 2p.",calculation:values=>`∂y/∂p = 1 × 2p = 1 × 2(${fmt(values.p)}) = ${fmt(values.gp)}`},
  {title:"3. Backpropagate through addition",explanation:"Addition has local derivative 1 for both inputs, so m and b each receive the arriving gradient.",calculation:values=>`∂y/∂m = ${fmt(values.gp)} × 1 = ${fmt(values.gm)} · ∂y/∂b = ${fmt(values.gp)} × 1 = ${fmt(values.gb)}`},
  {title:"4. Backpropagate through multiplication",explanation:"For m = xw, the local derivative with respect to x is w, and with respect to w is x.",calculation:values=>`∂y/∂x = ${fmt(values.gm)} × ${fmt(values.w)} = ${fmt(values.gx)} · ∂y/∂w = ${fmt(values.gm)} × ${fmt(values.x)} = ${fmt(values.gw)}`}
];
function updateGraph(){
  const values=graphValues();[["graphXValue",values.x],["graphWValue",values.w],["graphBValue",values.b]].forEach(([id,value])=>document.querySelector(`#${id}`).value=Number(value).toFixed(1).replace("-","−"));["X","W","B","M","P","Y"].forEach(name=>document.querySelector(`#node${name}`).textContent=fmt(values[name.toLowerCase()]));
  const gradients={Y:traceStep>=1?values.gy:null,P:traceStep>=2?values.gp:null,M:traceStep>=3?values.gm:null,B:traceStep>=3?values.gb:null,X:traceStep>=4?values.gx:null,W:traceStep>=4?values.gw:null};Object.entries(gradients).forEach(([name,value])=>document.querySelector(`#grad${name}`).textContent=value===null?"—":fmt(value));
  const active={1:["y"],2:["p"],3:["m","b"],4:["x","w"]}[traceStep]||[];document.querySelectorAll(".graph-visual article").forEach(node=>{const name=node.dataset.node;node.classList.toggle("active",active.includes(name));const completed=traceStep===4&&!active.includes(name)||traceStep===3&&["p","y"].includes(name)||traceStep===2&&name==="y";node.classList.toggle("complete",completed);});
  const step=traceSteps[traceStep];document.querySelector("#traceTitle").textContent=step.title;document.querySelector("#traceExplanation").textContent=step.explanation;document.querySelector("#traceCalculation").textContent=typeof step.calculation==="function"?step.calculation(values):step.calculation;document.querySelector("#previousTrace").disabled=traceStep===0;document.querySelector("#nextTrace").disabled=traceStep===4;document.querySelector("#nextTrace").textContent=traceStep===0?"Start backward pass":traceStep===4?"Trace complete":"Next backward step";
}
document.querySelectorAll("#graphX, #graphW, #graphB").forEach(input=>input.addEventListener("input",()=>{traceStep=0;updateGraph();}));document.querySelector("#nextTrace").addEventListener("click",()=>{traceStep=Math.min(4,traceStep+1);updateGraph();});document.querySelector("#previousTrace").addEventListener("click",()=>{traceStep=Math.max(0,traceStep-1);updateGraph();});document.querySelector("#resetTrace").addEventListener("click",()=>{traceStep=0;updateGraph();});

function updateChain(){const x=Number(document.querySelector("#chainX").value),u=2*x+1,y=u**2,local=2*u,total=local*2;document.querySelector("#chainXValue").value=x.toFixed(1).replace("-","−");document.querySelector("#chainXNode").textContent=fmt(x);document.querySelector("#chainUNode").textContent=fmt(u);document.querySelector("#chainYNode").textContent=fmt(y);document.querySelector("#localSquare").textContent=fmt(local);document.querySelector("#totalChain").textContent=fmt(total);document.querySelector("#chainMeaning").textContent=Math.abs(total)<.001?"At this point u equals zero, so the square has local slope zero. The product blocks sensitivity to x even though u still depends on x.":`A one-unit local change in x changes u by 2. At the current u, y changes by ${fmt(local)} per unit of u. Their product gives dy/dx = ${fmt(total)}.`;}
document.querySelector("#chainX").addEventListener("input",updateChain);

const gates={relu:{value:z=>Math.max(0,z),derivative:z=>z>0?1:0,label:"ReLU"},sigmoid:{value:z=>1/(1+Math.exp(-z)),derivative:z=>{const s=1/(1+Math.exp(-z));return s*(1-s);},label:"sigmoid"},tanh:{value:z=>Math.tanh(z),derivative:z=>1-Math.tanh(z)**2,label:"tanh"},linear:{value:z=>z,derivative:()=>1,label:"linear"}};
function updateGate(){const z=Number(document.querySelector("#gateZ").value),upstream=Number(document.querySelector("#upstreamGradient").value),name=document.querySelector("#gateActivation").value,gate=gates[name],local=gate.derivative(z),downstream=upstream*local;document.querySelector("#gateZValue").value=z.toFixed(1).replace("-","−");document.querySelector("#upstreamValue").value=upstream.toFixed(1).replace("-","−");document.querySelector("#gateUpstream").textContent=fmt(upstream);document.querySelector("#gateLocal").textContent=fmt(local);document.querySelector("#gateDownstream").textContent=fmt(downstream);document.querySelector("#gateMeaning").textContent=name==="relu"&&z<=0?"The ReLU gate is closed on this side, so its zero local slope blocks the arriving gradient. At exactly zero, the derivative is undefined and this lesson uses the common convention 0.":Math.abs(local)<.05?`${gate.label} is saturated here. The small local derivative shrinks the arriving gradient from ${fmt(upstream)} to ${fmt(downstream)}.`:`${gate.label} passes the upstream signal after scaling it by local slope ${fmt(local)} at the current z.`;}
document.querySelectorAll("#gateZ, #upstreamGradient, #gateActivation").forEach(input=>input.addEventListener("input",updateGate));

let branchMode="sum";
function updateBranch(){const x=Number(document.querySelector("#branchX").value),square=2*x,linear=3,total=square+linear,shown=branchMode==="sum"?total:linear;document.querySelector("#branchXValue").value=x.toFixed(1).replace("-","−");document.querySelector("#squareContribution").textContent=fmt(square);document.querySelector("#linearContribution").textContent=fmt(linear);document.querySelector("#branchTotal").textContent=fmt(shown);document.querySelector("#branchMeaning").textContent=branchMode==="sum"?`Correct: x influences y through both branches, so dy/dx = 2x + 3 = ${fmt(total)}.`:`Incorrect overwrite: keeping only the last path reports ${fmt(linear)} and loses the x² contribution ${fmt(square)}.`;}
document.querySelector("#branchX").addEventListener("input",updateBranch);document.querySelectorAll(".accumulation-choices button").forEach(button=>button.addEventListener("click",()=>{branchMode=button.dataset.mode;document.querySelectorAll(".accumulation-choices button").forEach(item=>item.classList.toggle("active",item===button));updateBranch();}));

const exampleGradients=[3,-1,4];let stateWeight=2,stateGradient=0,stateIndex=0,stateLast="Ready",stateEvents=[];
function renderState(){document.querySelector("#stateWeight").textContent=fmt(stateWeight);document.querySelector("#gradientBuffer").textContent=fmt(stateGradient);document.querySelector("#nextGradient").textContent=fmt(exampleGradients[stateIndex]);document.querySelector("#lastAction").textContent=stateLast;document.querySelector("#stateHistory").innerHTML=stateEvents.length?stateEvents.map(event=>`<li>${event}</li>`).join(""):"<li>No operations yet.</li>";document.querySelector("#stateMeaning").textContent=stateGradient===0?"The gradient buffer is clear. An independent batch can now calculate its own gradient.":stateLast==="Optimizer step"?"The optimizer used the buffer, but the gradient is still stored. Clear it before an independent batch or it will be counted again.":"Backward added to the existing buffer. This is useful only when the accumulation is intentional and correctly scaled.";}
document.querySelector("#backwardButton").addEventListener("click",()=>{const contribution=exampleGradients[stateIndex];stateGradient+=contribution;stateLast="Backward";stateEvents.unshift(`Backward added ${fmt(contribution)}; buffer is now ${fmt(stateGradient)}.`);stateIndex=(stateIndex+1)%exampleGradients.length;renderState();});
document.querySelector("#zeroButton").addEventListener("click",()=>{stateGradient=0;stateLast="Zero gradient";stateEvents.unshift("Gradient buffer cleared to 0.00.");renderState();});
document.querySelector("#stepButton").addEventListener("click",()=>{const before=stateWeight;stateWeight-=.1*stateGradient;stateLast="Optimizer step";stateEvents.unshift(`Weight update: ${fmt(before)} − 0.10 × ${fmt(stateGradient)} = ${fmt(stateWeight)}.`);renderState();});
document.querySelector("#stateReset").addEventListener("click",()=>{stateWeight=2;stateGradient=0;stateIndex=0;stateLast="Ready";stateEvents=[];renderState();});

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — you can trace the gradient mechanism.":"Not quite. Revisit the related interaction and try again.";})));
function completionState(){const done=CourseProgress.isComplete(7);document.querySelector("#completeLesson").textContent=done?"Lesson 7 completed ✓":"Mark Lesson 7 complete";document.querySelector("#completionStatus").textContent=done?"Your backward-pass contract is ready for autograd in Lesson 8.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(7);completionState();});window.addEventListener("course-progress",completionState);

updateGraph();updateChain();updateGate();updateBranch();renderState();completionState();
