"use strict";
CourseProgress.visit(3);

document.querySelectorAll(".readiness-choices button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".readiness-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#readinessFeedback").textContent=correct?"Correct. Training requires a numeric objective whose change can be measured.":"Not quite. Revisit prediction, error, and loss above.";}));

const truths=[3,5,7,9],basePredictions=[2,6,8,9];
function updateLosses(){const fourth=Number(document.querySelector("#outlierPrediction").value),predictions=[...basePredictions.slice(0,3),fourth],absolute=truths.map((value,index)=>Math.abs(predictions[index]-value)),squared=absolute.map(value=>value**2),mae=absolute.reduce((a,b)=>a+b,0)/truths.length,mse=squared.reduce((a,b)=>a+b,0)/truths.length;document.querySelector("#outlierValue").value=fourth;document.querySelector("#lossRows").innerHTML=truths.map((truth,index)=>`<tr><td>${index+1}</td><td>${truth}</td><td>${predictions[index]}</td><td>${absolute[index]}</td><td>${squared[index]}</td></tr>`).join("");document.querySelector("#maeValue").textContent=mae.toFixed(2);document.querySelector("#mseValue").textContent=mse.toFixed(2);const outlier=Math.abs(fourth-truths[3]);document.querySelector("#lossComparison").textContent=outlier<2?"With similarly sized errors, MAE and MSE remain relatively close.":`The fourth miss is ${outlier}. Squaring contributes ${outlier**2} to MSE, so that one example increasingly dominates.`;}
document.querySelector("#outlierPrediction").addEventListener("input",updateLosses);

function updateEntropy(){const probability=Number(document.querySelector("#correctProbability").value),loss=-Math.log(probability),canvas=document.querySelector("#entropyChart"),c=canvas.getContext("2d"),pad=42,w=canvas.width-pad*2,h=canvas.height-pad*2,maxLoss=4.7;document.querySelector("#probabilityValue").value=probability.toFixed(2);document.querySelector("#entropyValue").textContent=loss.toFixed(3);document.querySelector("#entropyMeaning").textContent=probability>.8?"The model gives the correct class high probability, so the penalty is small.":probability<.2?"The model gives the correct class little probability, so the penalty is severe.":"The model is uncertain; training still applies a meaningful penalty.";c.clearRect(0,0,canvas.width,canvas.height);c.strokeStyle="#dbe3ec";c.lineWidth=1;c.beginPath();c.moveTo(pad,pad);c.lineTo(pad,pad+h);c.lineTo(pad+w,pad+h);c.stroke();c.strokeStyle="#2864dc";c.lineWidth=3;c.beginPath();for(let i=1;i<=99;i++){const p=i/100,x=pad+p*w,y=pad+h-Math.min(-Math.log(p),maxLoss)/maxLoss*h;if(i===1)c.moveTo(x,y);else c.lineTo(x,y);}c.stroke();const px=pad+probability*w,py=pad+h-Math.min(loss,maxLoss)/maxLoss*h;c.fillStyle="#d64b59";c.beginPath();c.arc(px,py,6,0,Math.PI*2);c.fill();c.fillStyle="#637083";c.font="12px system-ui";c.fillText("low probability",pad,pad+h+22);c.fillText("high probability",pad+w-92,pad+h+22);}
document.querySelector("#correctProbability").addEventListener("input",updateEntropy);

const lossAt=weight=>(weight-4)**2,gradientAt=weight=>2*(weight-4);
function drawLandscape(){const weight=Number(document.querySelector("#landscapeWeight").value),loss=lossAt(weight),gradient=gradientAt(weight),canvas=document.querySelector("#landscapeChart"),c=canvas.getContext("2d"),pad=42,w=canvas.width-pad*2,h=canvas.height-pad*2,maxLoss=49,mapX=value=>pad+(value+3)/12*w,mapY=value=>pad+h-Math.min(value,maxLoss)/maxLoss*h;document.querySelector("#weightValue").value=weight.toFixed(1).replace("-","−");document.querySelector("#landscapeLoss").textContent=loss.toFixed(2);document.querySelector("#gradientValue").textContent=gradient.toFixed(2).replace("-","−");document.querySelector("#gradientDirection").textContent=Math.abs(gradient)<.05?"The local slope is flat at the minimum.":gradient<0?"Gradient is negative: increasing the weight moves downhill toward 4.":"Gradient is positive: decreasing the weight moves downhill toward 4.";c.clearRect(0,0,canvas.width,canvas.height);c.strokeStyle="#dbe3ec";c.beginPath();c.moveTo(pad,pad);c.lineTo(pad,pad+h);c.lineTo(pad+w,pad+h);c.stroke();c.strokeStyle="#2864dc";c.lineWidth=3;c.beginPath();for(let i=0;i<=120;i++){const x=-3+i/10,y=lossAt(x);if(i===0)c.moveTo(mapX(x),mapY(y));else c.lineTo(mapX(x),mapY(y));}c.stroke();c.fillStyle="#d64b59";c.beginPath();c.arc(mapX(weight),mapY(loss),7,0,Math.PI*2);c.fill();c.fillStyle="#0f9384";c.beginPath();c.arc(mapX(4),mapY(0),6,0,Math.PI*2);c.fill();c.fillStyle="#637083";c.font="12px system-ui";c.fillText("best weight = 4",mapX(4)+8,mapY(0)-8);updateFinite();}
document.querySelector("#landscapeWeight").addEventListener("input",drawLandscape);

function updateFinite(){const weight=Number(document.querySelector("#landscapeWeight").value),epsilon=Number(document.querySelector("#epsilon").value),left=lossAt(weight-epsilon),right=lossAt(weight+epsilon),estimate=(right-left)/(2*epsilon),exact=gradientAt(weight);document.querySelector("#epsilonValue").value=epsilon.toFixed(2);document.querySelector("#leftLoss").textContent=left.toFixed(3);document.querySelector("#rightLoss").textContent=right.toFixed(3);document.querySelector("#finiteGradient").textContent=estimate.toFixed(3);document.querySelector("#exactGradient").textContent=exact.toFixed(3);document.querySelector("#finiteMeaning").textContent=`The estimate samples loss at weight ${weight.toFixed(2)} − ${epsilon.toFixed(2)} and + ${epsilon.toFixed(2)}. For this smooth quadratic, the centered estimate matches the exact gradient closely.`;}
document.querySelector("#epsilon").addEventListener("input",updateFinite);

const rates=[.001,.15,.7,1.1],colors={"0.001":"#8290a4","0.15":"#0f9384","0.7":"#d68c27","1.1":"#d64b59"};let selectedRate=.15;
function trajectory(rate,steps){let weight=-1;const points=[];for(let step=0;step<=steps;step++){points.push({weight,loss:lossAt(weight)});weight-=rate*gradientAt(weight);}return points;}
function updateOptimization(){const steps=Number(document.querySelector("#stepCount").value),canvas=document.querySelector("#optimizationChart"),c=canvas.getContext("2d"),pad=45,w=canvas.width-pad*2,h=canvas.height-pad*2,all=Object.fromEntries(rates.map(rate=>[rate,trajectory(rate,steps)])),maxLog=Math.max(...Object.values(all).flat().map(point=>Math.log1p(point.loss))),mapX=step=>pad+step/steps*w,mapY=loss=>pad+h-Math.log1p(loss)/maxLog*h;c.clearRect(0,0,canvas.width,canvas.height);c.strokeStyle="#dbe3ec";c.beginPath();c.moveTo(pad,pad);c.lineTo(pad,pad+h);c.lineTo(pad+w,pad+h);c.stroke();rates.forEach(rate=>{c.strokeStyle=colors[String(rate)];c.lineWidth=rate===selectedRate?4:2;c.beginPath();all[rate].forEach((point,index)=>{if(index===0)c.moveTo(mapX(index),mapY(point.loss));else c.lineTo(mapX(index),mapY(point.loss));});c.stroke();});c.fillStyle="#637083";c.font="12px system-ui";c.fillText("training step",pad+w-75,pad+h+25);c.fillText("loss (log scale)",pad,pad-12);const final=all[selectedRate][steps];document.querySelector("#stepCountValue").value=steps;document.querySelector("#selectedRate").textContent=selectedRate;document.querySelector("#finalWeight").textContent=final.weight.toFixed(4);document.querySelector("#finalLoss").textContent=final.loss.toFixed(4);document.querySelector("#rateDiagnosis").textContent=selectedRate===.001?"Stable but extremely slow: after these steps the parameter remains far from 4.":selectedRate===.15?"A useful rate here: loss falls smoothly and quickly.":selectedRate===.7?"The parameter overshoots 4 and alternates sides, but the oscillations shrink.":"Divergence: every overshoot grows, so loss trends upward.";}
document.querySelectorAll(".rate-buttons button").forEach(button=>button.addEventListener("click",()=>{selectedRate=Number(button.dataset.rate);document.querySelectorAll(".rate-buttons button").forEach(item=>item.classList.toggle("active",item===button));updateOptimization();}));document.querySelector("#stepCount").addEventListener("input",updateOptimization);

const groupColors=["#2864dc","#0f9384","#d68c27","#9b61c8","#d64b59","#537286","#bd6d33","#36735e","#6c75c9","#b05d7c","#71803a","#8a6b50"];
function updateBatch(size){const host=document.querySelector("#batchVisual"),groups=12/size;host.innerHTML="";for(let i=0;i<12;i++){const example=document.createElement("span");example.className="batch-example";example.textContent=i+1;example.style.setProperty("--group-color",groupColors[Math.floor(i/size)]);host.appendChild(example);if((i+1)%size===0&&i<11){const divider=document.createElement("i");divider.className="batch-divider";host.appendChild(divider);}}document.querySelector("#batchSizeValue").textContent=size;document.querySelector("#updatesValue").textContent=groups;document.querySelector("#noiseValue").textContent=size===12?"Most stable":size===1?"Most noisy":"Balanced";document.querySelector("#batchMeaning").textContent=size===12?"All twelve examples contribute to one update. The estimate is stable, but updates are infrequent.":size===1?"Every example causes an update. The path reacts quickly but varies strongly from example to example.":"Four examples contribute to each of three updates: a practical balance between stability and frequency.";}
document.querySelectorAll(".batch-buttons button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".batch-buttons button").forEach(item=>item.classList.toggle("active",item===button));updateBatch(Number(button.dataset.batch));}));

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — you can explain the mechanism.":"Not quite. Revisit the related example and try again.";})));
function completionState(){const done=CourseProgress.isComplete(3);document.querySelector("#completeLesson").textContent=done?"Lesson 3 completed ✓":"Mark Lesson 3 complete";document.querySelector("#completionStatus").textContent=done?"Your course dashboard has been updated.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(3);completionState();});window.addEventListener("course-progress",completionState);

updateLosses();updateEntropy();drawLandscape();updateOptimization();updateBatch(12);completionState();
