"use strict";

const api=`http://${location.hostname}:8081`;
const status=document.querySelector("#apiStatus"),history=document.querySelector("#history"),formStatus=document.querySelector("#formStatus"),guide=document.querySelector("#activityGuide"),lessonSelect=document.querySelector("#lesson");
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

async function loadActivity(){const lesson=Number(lessonSelect.value),id=`L${String(lesson).padStart(2,"0")}-A1`;try{const activity=await fetch(`../../activities/${id}.json`).then(response=>{if(!response.ok)throw new Error("activity unavailable");return response.json();});guide.innerHTML=`<h3>${escapeHtml(activity.title)}</h3><p>${escapeHtml(activity.mission)}</p><p><strong>Estimated time:</strong> ${activity.estimated_minutes} minutes</p><ol>${["guided","challenge","engineer_extension"].map((level,index)=>`<li><strong>${index===0?"Guided":index===1?"Challenge":"Engineer extension · optional"}</strong><br>${escapeHtml(activity.levels[level].objective)}</li>`).join("")}</ol><p><strong>Save:</strong> ${escapeHtml(activity.artifact.path_or_download)}</p><p><a href="../../lessons/${["01_linear_regression","02_vectors_matrices_tensors","03_loss_functions_and_optimization"][lesson-1]}/index.html#ai-story">Open this activity in the lesson</a></p>`;}catch(error){guide.innerHTML="<p>The activity guide could not be loaded. Open the matching lesson from the course page.</p>";}}

async function loadEvidence(){try{const health=await fetch(`${api}/health`);if(!health.ok)throw new Error("health check failed");status.textContent="Connected";status.className="status-ok";const data=await fetch(`${api}/api/experiments`).then(response=>response.json());history.innerHTML=data.experiments.length?data.experiments.map(item=>`<article><strong>${escapeHtml(item.activity_id)}</strong><p><b>Prediction:</b> ${escapeHtml(item.hypothesis)}</p><p><b>Observed:</b> ${escapeHtml(item.observation)}</p><p><b>Conclusion:</b> ${escapeHtml(item.conclusion)}</p><small>${escapeHtml(item.created_at)}</small></article>`).join(""):"<p>No evidence saved yet.</p>";}catch(error){status.textContent="Unavailable";status.className="status-error";history.innerHTML="<p>The activity guide still works. Start the Foundations profile to save evidence persistently.</p>";}}

document.querySelector("#experimentForm").addEventListener("submit",async event=>{event.preventDefault();const lesson=Number(lessonSelect.value),payload={lesson,activity_id:`L${String(lesson).padStart(2,"0")}-A1`,hypothesis:document.querySelector("#hypothesis").value,observation:document.querySelector("#observation").value,conclusion:document.querySelector("#conclusion").value};try{const response=await fetch(`${api}/api/experiments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();formStatus.textContent=response.ok?"Evidence saved.":body.error;formStatus.className=response.ok?"status-ok":"status-error";if(response.ok)loadEvidence();}catch(error){formStatus.textContent="The evidence service is unavailable. Keep your notes here, then copy them into the activity worksheet.";formStatus.className="status-error";}});
lessonSelect.addEventListener("change",loadActivity);
loadActivity();loadEvidence();
