"use strict";

CourseProgress.visit(9);

document.querySelectorAll(".readiness-choices button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".readiness-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#readinessFeedback").textContent=correct?"Correct. Optimization is still reducing training error, but the widening validation gap suggests the model is learning details that do not transfer.":"Not quite. Training loss describes fit to training examples; validation loss asks whether that fit transfers.";}));

function updateSplit(changed){const trainInput=document.querySelector("#trainShare"),validationInput=document.querySelector("#validationShare");let train=Number(trainInput.value),validation=Number(validationInput.value);if(train+validation>90){if(changed==="train")validation=90-train;else train=90-validation;trainInput.value=train;validationInput.value=validation;}const test=100-train-validation,strategy=document.querySelector("#splitStrategy").value,leak=document.querySelector("#duplicateLeak").checked;document.querySelector("#trainShareValue").value=`${train}%`;document.querySelector("#validationShareValue").value=`${validation}%`;document.querySelector("#trainCount").textContent=(train*100).toLocaleString();document.querySelector("#validationCount").textContent=(validation*100).toLocaleString();document.querySelector("#testCount").textContent=(test*100).toLocaleString();document.querySelector("#splitBar").innerHTML=`<span class="split-train" style="width:${train}%">Train ${train}%</span><span class="split-validation" style="width:${validation}%">Validation ${validation}%</span><span class="split-test" style="width:${test}%">Test ${test}%</span>`;const strategyText={random:"Random splitting assumes records are independent. Confirm that no customer, route, event, or duplicate ties examples across partitions.",customer:"Grouping by customer measures transfer to customers the model did not see during training.",time:"A time split trains on earlier shipments and evaluates later ones, matching a future-deployment question."}[strategy];document.querySelector("#splitMeaning").textContent=leak?"Leakage warning: related records may cross boundaries. A model can appear to generalize while recognizing customer- or event-specific patterns already seen during training.":`${strategyText} The test partition stays sealed until model selection is complete.`;}
document.querySelector("#trainShare").addEventListener("input",()=>updateSplit("train"));document.querySelector("#validationShare").addEventListener("input",()=>updateSplit("validation"));document.querySelectorAll("#splitStrategy, #duplicateLeak").forEach(input=>input.addEventListener("change",()=>updateSplit()));

function updateBatch(){const size=Number(document.querySelector("#batchSize").value),epochs=Number(document.querySelector("#epochCount").value),shuffle=document.querySelector("#shuffleBatches").checked,batches=Math.ceil(1000/size);document.querySelector("#epochCountValue").value=epochs;document.querySelector("#batchesPerEpoch").textContent=batches;document.querySelector("#totalUpdates").textContent=(batches*epochs).toLocaleString();const shown=Math.min(batches,12);document.querySelector("#batchPreview").innerHTML=Array.from({length:shown},(_,i)=>`<span class="batch-chip">Batch ${i+1} · ${size}</span>`).join("")+(batches>shown?`<span class="batch-chip">+ ${batches-shown} more</span>`:"");document.querySelector("#batchMeaning").textContent=`Each epoch covers all 1,000 planned examples in ${batches} updates. Across ${epochs} epochs, the optimizer steps ${batches*epochs} times. ${shuffle?"Shuffling creates new batch groupings each epoch while preserving the same examples.":"Without shuffling, the same ordered neighbors repeatedly influence each update together; meaningful ordering can bias the optimization path."}`;}
document.querySelectorAll("#batchSize, #epochCount, #shuffleBatches").forEach(input=>input.addEventListener("input",updateBatch));

const seedOffsets={11:0,23:.018,47:-.012};
function trainingSeries(rate,seed){return Lesson09Logic.trainingSeries(rate,seed);}
function renderChart(train,validation,bestIndex){const width=820,height=260,pad=38,max=1,min=.1,x=i=>pad+i*(width-pad*2)/(train.length-1),y=value=>height-pad-(value-min)*(height-pad*2)/(max-min),grid=[.2,.4,.6,.8,1];const trainPoints=train.map((v,i)=>`${x(i)},${y(v)}`).join(" "),validationPoints=validation.map((v,i)=>`${x(i)},${y(v)}`).join(" ");document.querySelector("#trainingChart").innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Loss by epoch"><line class="chart-axis" x1="${pad}" y1="10" x2="${pad}" y2="${height-pad}"/><line class="chart-axis" x1="${pad}" y1="${height-pad}" x2="${width-8}" y2="${height-pad}"/>${grid.map(v=>`<line class="chart-grid" x1="${pad}" y1="${y(v)}" x2="${width-8}" y2="${y(v)}"/><text class="chart-label" x="2" y="${y(v)+4}">${v.toFixed(1)}</text>`).join("")}<line class="chart-best" x1="${x(bestIndex)}" y1="10" x2="${x(bestIndex)}" y2="${height-pad}"/><text class="chart-label" x="${Math.min(width-90,x(bestIndex)+5)}" y="22">best epoch ${bestIndex+1}</text><polyline class="chart-train" points="${trainPoints}"/><polyline class="chart-validation" points="${validationPoints}"/><text class="chart-label" x="${width-55}" y="${height-5}">epoch</text></svg>`;}
document.querySelector("#runTraining").addEventListener("click",()=>{const rate=document.querySelector("#learningRate").value,seed=document.querySelector("#trainingSeed").value,{train,validation}=trainingSeries(rate,seed),best=Math.min(...validation),bestIndex=validation.indexOf(best);renderChart(train,validation,bestIndex);document.querySelector("#bestEpoch").textContent=bestIndex+1;document.querySelector("#bestValidationLoss").textContent=best.toFixed(3);document.querySelector("#finalTrainingLoss").textContent=train.at(-1).toFixed(3);const diagnosis=rate==="slow"?"Still improving slowly":rate==="high"?"Unstable updates":"Validation turns upward";document.querySelector("#trainingDiagnosis").textContent=diagnosis;document.querySelector("#trainingMeaning").textContent=rate==="slow"?"This learning rate makes consistent but limited progress within 30 epochs. More time may help, but the experiment budget must be applied consistently across candidates.":rate==="high"?"Large parameter steps overshoot useful regions and make both curves oscillate. A lower learning rate is the direct response.":`The best validation result occurs at epoch ${bestIndex+1}. Training loss continues down afterward while validation worsens, so the last checkpoint is not the strongest candidate.`;});

const validationTrace=[.78,.65,.54,.46,.39,.34,.30,.27,.25,.235,.224,.216,.209,.205,.201,.199,.196,.197,.201,.206];
function updateStopping(){const patience=Number(document.querySelector("#patience").value),delta=Number(document.querySelector("#minimumImprovement").value);document.querySelector("#patienceValue").value=`${patience} epoch${patience===1?"":"s"}`;let best=Infinity,bestIndex=-1,wait=0,stopped=validationTrace.length;const states=[];for(let i=0;i<validationTrace.length;i++){if(validationTrace[i]<best-delta){best=validationTrace[i];bestIndex=i;wait=0;states.push("best");}else{wait++;states.push("waiting");if(wait>=patience){stopped=i+1;break;}}}document.querySelector("#stoppingTimeline").innerHTML=validationTrace.map((value,i)=>`<div class="epoch-card ${i>=stopped?"stopped":states[i]||"stopped"}"><small>E${i+1}</small><strong>${value.toFixed(3)}</strong></div>`).join("");document.querySelector("#stoppingBest").textContent=`Epoch ${bestIndex+1} · ${best.toFixed(3)}`;document.querySelector("#stopEpoch").textContent=stopped<validationTrace.length?`Epoch ${stopped}`:"Not within trace";document.querySelector("#stopReason").textContent=stopped<validationTrace.length?`${patience} non-qualifying result${patience===1?"":"s"}`:"Patience not exhausted";document.querySelector("#stoppingMeaning").textContent=`An improvement must beat the saved best by more than ${delta.toFixed(3)}. The patience counter resets only on a qualifying improvement. Training may stop later, but restoration uses epoch ${bestIndex+1}.`;}
document.querySelectorAll("#patience, #minimumImprovement").forEach(input=>input.addEventListener("input",updateStopping));

const labels=["On time","Slightly late","Severely late"],matrix=[[630,45,25],[55,150,25],[12,28,30]];
function renderMatrix(){let html='<div class="matrix-label">Actual ↓ / Predicted →</div>'+labels.map(label=>`<div class="matrix-label">${label}</div>`).join("");matrix.forEach((row,r)=>{html+=`<div class="matrix-label">${labels[r]}</div>`;row.forEach((count,c)=>{html+=`<button class="matrix-cell ${r===c?"correct":"error"}" data-row="${r}" data-column="${c}">${count}</button>`;});});document.querySelector("#confusionMatrix").innerHTML=html;document.querySelectorAll(".matrix-cell").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".matrix-cell").forEach(item=>item.classList.remove("active"));button.classList.add("active");const r=Number(button.dataset.row),c=Number(button.dataset.column),count=matrix[r][c];document.querySelector("#selectedCell").textContent=`${count}: actual ${labels[r]} → predicted ${labels[c]}`;document.querySelector("#selectedCellMeaning").textContent=r===c?`These ${count} shipments were classified correctly.`:`These ${count} errors need investigation. Review representative records and ask what operational harm follows from mistaking ${labels[r].toLowerCase()} for ${labels[c].toLowerCase()}.`; }));const metrics=Lesson09Logic.matrixMetrics(matrix);document.querySelector("#accuracyMetric").textContent=`${(metrics.accuracy*100).toFixed(1)}%`;document.querySelector("#recallMetric").textContent=`${(metrics.severeRecall*100).toFixed(1)}%`;document.querySelector("#precisionMetric").textContent=`${(metrics.severePrecision*100).toFixed(1)}%`;}
const metricExplanations={accuracy:"Accuracy asks: out of all 1,000 shipments, what share received the correct class? It weights every shipment equally.",severeRecall:"Severe-late recall asks: out of all 70 shipments that were actually severely late, what share did the model detect? Missing one may prevent intervention.",severePrecision:"Severe-late precision asks: out of every shipment flagged severely late, what share truly was? Low precision wastes intervention capacity."};document.querySelectorAll(".metric-cards button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".metric-cards button").forEach(item=>item.classList.toggle("active",item===button));document.querySelector("#metricMeaning").textContent=metricExplanations[button.dataset.metric];}));

const seedScores=[.84,.79,.86,.73,.82];let visibleSeeds=0;
function renderSeeds(){const shown=seedScores.slice(0,visibleSeeds);document.querySelector("#seedResults").innerHTML=shown.length?shown.map((score,i)=>`<article class="seed-result"><small>SEED ${[11,23,47,71,89][i]}</small><strong>${(score*100).toFixed(1)}%</strong></article>`).join(""):'<article class="seed-result"><small>NO RUNS</small><strong>—</strong></article>';if(shown.length){const mean=shown.reduce((a,b)=>a+b,0)/shown.length,min=Math.min(...shown),max=Math.max(...shown);document.querySelector("#seedMean").textContent=`${(mean*100).toFixed(1)}%`;document.querySelector("#seedRange").textContent=`${(min*100).toFixed(1)}–${(max*100).toFixed(1)}%`;document.querySelector("#seedConclusion").textContent=shown.length===1?"One repeatable run":"Meaningful variability";document.querySelector("#seedMeaning").textContent=shown.length===1?"This run can be recreated under compatible conditions, but it does not show whether this result is typical. Compare several predetermined seeds.":`Across ${shown.length} runs, the spread is ${((max-min)*100).toFixed(1)} percentage points. Report the distribution and investigate failed runs instead of publishing only the best seed.`;}else{document.querySelector("#seedMean").textContent="—";document.querySelector("#seedRange").textContent="—";document.querySelector("#seedConclusion").textContent="Collect results first";document.querySelector("#seedMeaning").textContent="Run one seed to see repeatability, then five seeds to inspect robustness.";}}
document.querySelector("#runOneSeed").addEventListener("click",()=>{visibleSeeds=Math.min(seedScores.length,visibleSeeds+1);renderSeeds();});document.querySelector("#runFiveSeeds").addEventListener("click",()=>{visibleSeeds=5;renderSeeds();});document.querySelector("#resetSeeds").addEventListener("click",()=>{visibleSeeds=0;renderSeeds();});

document.querySelector("#evaluateRelease").addEventListener("click",()=>{const checkpoint=document.querySelector("#releaseCheckpoint").value,group=document.querySelector("#groupAudit").checked,repeats=document.querySelector("#repeatAudit").checked,frozen=document.querySelector("#frozenTest").checked,result=document.querySelector("#releaseResult"),reasons=[];if(checkpoint==="last")reasons.push("the last checkpoint replaces the better validated epoch 17 state");if(checkpoint==="test")reasons.push("the test set was used for selection");if(!group)reasons.push("subgroup errors were not audited");if(!repeats)reasons.push("seed robustness was not measured");if(!frozen)reasons.push("the test boundary was not protected");const pass=!reasons.length;result.className=`release-result ${pass?"pass":"fail"}`;result.innerHTML=pass?"<strong>Release evidence is structurally complete</strong><p>The best validation checkpoint was selected before a sealed final test, with subgroup and repeated-run evidence. Business thresholds still require stakeholder approval.</p>":`<strong>Do not release yet</strong><p>${reasons.join("; ")}.</p>`;});

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — the evidence boundary is intact.":"Not quite. Revisit the related interaction and explain which state or evidence may influence the decision.";})));
function completionState(){const done=CourseProgress.isComplete(9);document.querySelector("#completeLesson").textContent=done?"Lesson 9 completed ✓":"Mark Lesson 9 complete";document.querySelector("#completionStatus").textContent=done?"Your training and evaluation protocol is ready for Lesson 10's generalization controls.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(9);completionState();});window.addEventListener("course-progress",completionState);

updateSplit();updateBatch();updateStopping();renderMatrix();document.querySelector("#metricMeaning").textContent=metricExplanations.accuracy;renderSeeds();completionState();
