"use strict";

CourseProgress.visit(10);

document.querySelectorAll(".readiness-choices button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".readiness-choices button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.correct==="true";button.classList.add(correct?"correct":"wrong");document.querySelector("#readinessFeedback").textContent=correct?"Correct. The training fit is improving while transfer to validation evidence is getting worse. Next verify the boundary and then test a controlled response.":"Not quite. A trustworthy validation split is moving in the opposite direction from training, which describes a widening generalization gap.";}));

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const chartWidth=820,chartHeight=270,chartPad=28;
const chartX=value=>chartPad+value*(chartWidth-chartPad*2);
const chartY=value=>chartHeight-chartPad-value*(chartHeight-chartPad*2);
function deterministicNoise(index){const raw=Math.sin((index+1)*12.9898)*43758.5453;return((raw-Math.floor(raw))*2-1);}
function truth(x){return .5+.22*Math.sin(x*Math.PI*2)+.12*x;}
function updateFit(){
  const capacity=Number(document.querySelector("#capacity").value),evidence=Number(document.querySelector("#evidence").value),noise=Number(document.querySelector("#noise").value),regularization=Number(document.querySelector("#regularization").value);
  const model=Lesson10Logic.fitModel(capacity,evidence,noise,regularization);
  document.querySelector("#capacityValue").value=capacity;document.querySelector("#evidenceValue").value=evidence;document.querySelector("#noiseValue").value=["low","medium","high"][noise];document.querySelector("#regularizationValue").value=["none","light","moderate","strong","very strong"][regularization];
  const points=model.xs.map((x,i)=>`<circle class="data-point" cx="${chartX(x)}" cy="${chartY(clamp(model.ys[i],.03,.97))}" r="3"/>`).join("");
  const truthPoints=Array.from({length:101},(_,i)=>{const x=i/100;return`${chartX(x)},${chartY(truth(x))}`;}).join(" ");
  const modelPoints=Array.from({length:101},(_,i)=>{const x=i/100;return`${chartX(x)},${chartY(clamp(model.predict(x),.02,.98))}`;}).join(" ");
  document.querySelector("#fitChart").innerHTML=`<svg viewBox="0 0 ${chartWidth} ${chartHeight}" role="img" aria-label="Noisy observations, stable relationship, and fitted polynomial model"><line class="chart-axis" x1="${chartPad}" y1="8" x2="${chartPad}" y2="${chartHeight-chartPad}"/><line class="chart-axis" x1="${chartPad}" y1="${chartHeight-chartPad}" x2="${chartWidth-8}" y2="${chartHeight-chartPad}"/>${[.25,.5,.75].map(v=>`<line class="chart-grid" x1="${chartPad}" y1="${chartY(v)}" x2="${chartWidth-8}" y2="${chartY(v)}"/>`).join("")}<polyline class="truth-line" points="${truthPoints}"/>${points}<polyline class="model-line" points="${modelPoints}"/><text class="chart-label" x="45" y="20">dashed: stable relationship · blue: fitted model · orange: observations</text></svg>`;
  const train=model.trainError,validation=model.validationError,gap=validation-train,referenceTrain=Lesson10Logic.fitModel(10,evidence,noise,regularization).trainError,diagnosis=Lesson10Logic.diagnoseFit(model,referenceTrain);let meaning;
  if(diagnosis==="Underfitting"){meaning="Training error is more than three times the best displayed capacity can achieve under the same evidence. The fitted polynomial is missing stable structure.";}else if(diagnosis==="Overfitting risk"){meaning="Validation error is more than 2.5 times training error. The curve is fitting training-specific detail that does not transfer.";}else{meaning="Training and validation errors are reasonably low and proportionate. Confirm the pattern across new samples and deployment-like shifts.";}
  document.querySelector("#fitTrainError").textContent=train.toFixed(3);document.querySelector("#fitValidationError").textContent=validation.toFixed(3);document.querySelector("#fitGap").textContent=gap.toFixed(3);document.querySelector("#fitDiagnosis").textContent=diagnosis;document.querySelector("#fitMeaning").textContent=meaning;
}
document.querySelectorAll("#capacity, #evidence, #noise, #regularization").forEach(input=>input.addEventListener("input",updateFit));

const curvePatterns={bias:{train:[.52,.47,.44,.42,.41,.40],validation:[.66,.58,.53,.49,.47,.46],training:"Improves slightly, then remains weak",validationText:"Approaches the same high-error region",action:"Improve features, optimization, or capacity",meaning:"The small gap is not automatically good: both errors are high. More of the same data is unlikely to solve a representation or capacity limitation by itself."},variance:{train:[.08,.09,.10,.11,.12,.13],validation:[.52,.42,.34,.29,.25,.23],training:"Very strong across sample sizes",validationText:"Improves as evidence grows; gap remains",action:"Add representative data or constrain fit",meaning:"The model fits training data much better than validation data. The closing gap suggests that broader representative evidence can help, while regularization may also reduce sensitivity."},healthy:{train:[.29,.25,.22,.20,.19,.18],validation:[.39,.31,.26,.23,.21,.20],training:"Improves and stabilizes",validationText:"Converges toward training performance",action:"Validate on shifts and important subgroups",meaning:"Both curves reach a low-error region with a modest gap. More data may still help, but the next question is whether this evidence represents deployment."}};
let selectedCurve="bias";
function renderLearningCurve(){const pattern=curvePatterns[selectedCurve],xs=[.05,.18,.35,.55,.76,.96],mapPoints=values=>values.map((v,i)=>`${chartX(xs[i])},${chartY(1-v)}`).join(" ");document.querySelector("#learningCurveChart").innerHTML=`<svg viewBox="0 0 ${chartWidth} ${chartHeight}" role="img" aria-label="Training and validation performance by sample count"><line class="chart-axis" x1="${chartPad}" y1="8" x2="${chartPad}" y2="${chartHeight-chartPad}"/><line class="chart-axis" x1="${chartPad}" y1="${chartHeight-chartPad}" x2="${chartWidth-8}" y2="${chartHeight-chartPad}"/>${[.25,.5,.75].map(v=>`<line class="chart-grid" x1="${chartPad}" y1="${chartY(v)}" x2="${chartWidth-8}" y2="${chartY(v)}"/>`).join("")}<polyline class="train-line" points="${mapPoints(pattern.train)}"/><polyline class="validation-line" points="${mapPoints(pattern.validation)}"/><text class="chart-label" x="40" y="18">higher is better · blue training · orange validation</text><text class="chart-label" x="${chartWidth-100}" y="${chartHeight-7}">more data →</text></svg>`;document.querySelector("#curveTraining").textContent=pattern.training;document.querySelector("#curveValidation").textContent=pattern.validationText;document.querySelector("#curveAction").textContent=pattern.action;document.querySelector("#curveMeaning").textContent=pattern.meaning;}
document.querySelectorAll(".curve-buttons button").forEach(button=>button.addEventListener("click",()=>{selectedCurve=button.dataset.curve;document.querySelectorAll(".curve-buttons button").forEach(item=>item.classList.toggle("active",item===button));renderLearningCurve();}));

const baseWeights=[2.4,-1.8,.9,.4,-.15,.05];let penaltyType="l2";
function updatePenalty(){const strength=Number(document.querySelector("#penaltyStrength").value)/100;document.querySelector("#penaltyStrengthValue").value=strength.toFixed(2);const weights=baseWeights.map(value=>penaltyType==="none"?value:penaltyType==="l2"?value/(1+strength*2):Math.sign(value)*Math.max(0,Math.abs(value)-strength*1.2));document.querySelector("#weightBars").innerHTML=weights.map((value,i)=>{const width=Math.abs(value)/2.4*48,left=value>=0?50:50-width;return`<div class="weight-row"><strong>w${i+1}</strong><div class="weight-track"><span class="weight-zero"></span><span class="weight-fill ${value<0?"negative":""}" style="left:${left}%;width:${width}%"></span></div><span>${value.toFixed(2)}</span></div>`;}).join("");const nonzero=weights.filter(value=>Math.abs(value)>.0001).length,largest=Math.max(...weights.map(Math.abs));document.querySelector("#nonzeroWeights").textContent=`${nonzero} / ${weights.length}`;document.querySelector("#largestWeight").textContent=largest.toFixed(2);document.querySelector("#penaltyEffect").textContent=penaltyType==="none"?"Fit data loss only":penaltyType==="l2"?"Smooth shrinkage":"Sparse weights";document.querySelector("#penaltyMeaning").textContent=penaltyType==="none"?"No weight penalty is added. Model complexity is still affected by architecture, data, augmentation, dropout, and training duration.":penaltyType==="l2"?"L2 pressure grows with weight magnitude. All displayed weights shrink smoothly in this illustration; validation evidence must choose a useful strength.":"L1 applies constant-magnitude pressure away from zero in this illustration, so smaller weights reach exactly zero first. Sparsity does not guarantee better predictions.";}
document.querySelectorAll(".penalty-buttons button").forEach(button=>button.addEventListener("click",()=>{penaltyType=button.dataset.penalty;document.querySelectorAll(".penalty-buttons button").forEach(item=>item.classList.toggle("active",item===button));updatePenalty();}));document.querySelector("#penaltyStrength").addEventListener("input",updatePenalty);

let dropMode="train",dropRun=0;
function renderDropout(){const rate=Number(document.querySelector("#dropRate").value)/100,active=dropMode==="eval"?8:Math.round(8*(1-rate)),start=dropRun%8,kept=new Set(Array.from({length:active},(_,i)=>(start+i*3)%8)),scale=dropMode==="eval"||rate===0?1:1/(1-rate);document.querySelector("#dropRateValue").value=`${Math.round(rate*100)}%`;document.querySelector("#dropoutUnits").innerHTML=Array.from({length:8},(_,i)=>`<div class="dropout-unit ${kept.has(i)?"":"dropped"}">${kept.has(i)?(2*scale).toFixed(2):"0"}</div>`).join("");document.querySelector("#activeUnits").textContent=`${kept.size} / 8`;document.querySelector("#survivorScale").textContent=`× ${scale.toFixed(2)}`;document.querySelector("#dropoutStability").textContent=dropMode==="eval"?"Stable":"Varies by pass";document.querySelector("#dropoutMeaning").textContent=dropMode==="eval"?"Evaluation uses the full network with no random mask. Changing the configured drop probability has no effect until training mode resumes.":rate===0?"A zero drop probability leaves every activation active, so this layer adds no dropout regularization.":`Training drops approximately ${Math.round(rate*100)}% of activations and rescales survivors by 1 ÷ (1 − ${rate.toFixed(2)}) = ${scale.toFixed(2)}. Run again to observe a different temporary subnetwork.`;}
document.querySelector("#runDropout").addEventListener("click",()=>{dropRun++;renderDropout();});document.querySelector("#dropRate").addEventListener("input",renderDropout);document.querySelectorAll(".dropout-buttons button").forEach(button=>button.addEventListener("click",()=>{dropMode=button.dataset.dropMode;dropRun=0;document.querySelectorAll(".dropout-buttons button").forEach(item=>item.classList.toggle("active",item===button));renderDropout();}));

const augmentationPolicies={vision:[{title:"Slight brightness change",detail:"Simulates plausible lighting variation.",safe:true},{title:"Crop that preserves the full object",detail:"Changes framing without changing identity.",safe:true},{title:"Mirror a left-turn traffic sign",detail:"Changes the sign's semantic direction.",safe:false},{title:"Rotate an upright radiograph 180°",detail:"May create an implausible clinical orientation.",safe:false}],text:[{title:"Paraphrase while preserving delivery intent",detail:"Changes wording but keeps the target intent.",safe:true},{title:"Inject a common keyboard typo",detail:"Models realistic input noise without changing intent.",safe:true},{title:"Delete the word “not”",detail:"Can reverse the meaning and therefore the label.",safe:false},{title:"Randomly reorder every word",detail:"Usually destroys syntax and meaning.",safe:false}],tabular:[{title:"Add sensor noise within calibration tolerance",detail:"Models plausible measurement variation.",safe:true},{title:"Mask an optional field sometimes missing in production",detail:"Teaches robustness to an expected absence pattern.",safe:true},{title:"Change actual delivery outcome but keep the label",detail:"Creates a contradiction between evidence and target.",safe:false},{title:"Create a negative route distance",detail:"Produces an impossible operational record.",safe:false}]};let augmentationDomain="vision",augmentationAnswers={};
function renderAugmentations(){const items=augmentationPolicies[augmentationDomain];document.querySelector("#augmentationCards").innerHTML=items.map((item,i)=>`<article class="augmentation-card ${augmentationAnswers[i]===undefined?"":augmentationAnswers[i]===item.safe?"correct":"wrong"}"><h3>${item.title}</h3><p>${item.detail}</p><div class="augmentation-actions"><button data-index="${i}" data-answer="true">Safe</button><button data-index="${i}" data-answer="false">Unsafe</button></div></article>`).join("");document.querySelectorAll(".augmentation-actions button").forEach(button=>button.addEventListener("click",()=>{augmentationAnswers[Number(button.dataset.index)]=button.dataset.answer==="true";renderAugmentations();}));const entries=Object.entries(augmentationAnswers),correct=entries.filter(([i,answer])=>answer===items[Number(i)].safe).length;document.querySelector("#augmentationReviewed").textContent=`${entries.length} / 4`;document.querySelector("#augmentationCorrect").textContent=correct;document.querySelector("#augmentationMeaning").textContent=entries.length<4?"A safe transformation must remain plausible and preserve the label under the exact prediction task.":correct===4?"All four decisions preserve the target contract. Augmentation policies should still be validated against real examples and subgroup behavior.":"Review the highlighted mistakes. Plausibility and label preservation matter more than whether a transformation is commonly used elsewhere.";}
document.querySelectorAll(".domain-buttons button").forEach(button=>button.addEventListener("click",()=>{augmentationDomain=button.dataset.domain;augmentationAnswers={};document.querySelectorAll(".domain-buttons button").forEach(item=>item.classList.toggle("active",item===button));renderAugmentations();}));

function updateScale(){const distanceSpread=Number(document.querySelector("#distanceSpread").value),delaySpread=Number(document.querySelector("#delaySpread").value),distanceZ=(600-300)/distanceSpread,delayZ=(3-2)/delaySpread,maxZ=Math.max(Math.abs(distanceZ),Math.abs(delayZ),.01);document.querySelector("#distanceSpreadValue").value=`${distanceSpread} miles`;document.querySelector("#delaySpreadValue").value=`${delaySpread} hour${delaySpread===1?"":"s"}`;document.querySelector("#rawDistance").style.width="100%";document.querySelector("#rawDelay").style.width="2%";document.querySelector("#standardizedValues").textContent=`distance ${distanceZ.toFixed(2)} · delay ${delayZ.toFixed(2)}`;document.querySelector("#standardDistance").style.width=`${Math.abs(distanceZ)/maxZ*100}%`;document.querySelector("#standardDelay").style.width=`${Math.abs(delayZ)/maxZ*100}%`;document.querySelector("#scaleMeaning").textContent=`Using training means of 300 miles and 2 hours, the shipment is ${distanceZ.toFixed(2)} distance standard deviations and ${delayZ.toFixed(2)} delay standard deviations above the mean. Standardization changes numerical conditioning, not which examples are correct.`;}
document.querySelectorAll("#distanceSpread, #delaySpread").forEach(input=>input.addEventListener("input",updateScale));

document.querySelector("#diagnoseStrategy").addEventListener("click",()=>{const train=document.querySelector("#strategyTrain").value,validation=document.querySelector("#strategyValidation").value,gap=document.querySelector("#strategyGap").value,data=document.querySelector("#strategyData").value,result=document.querySelector("#strategyResult");let kind,title,message;if(data==="suspect"){kind="warning";title="Repair evidence before regularizing";message="Audit leakage, labels, preprocessing scope, split overlap, and metric aggregation. A penalty cannot make a compromised experiment trustworthy.";}else if(train==="weak"){kind="bias";title="Investigate underfitting or optimization";message="Both fitting ability and representation may be limiting. Verify gradients and learning rate, improve features, or test sufficient capacity before adding stronger constraints.";}else if(validation==="weak"&&(gap==="closing"||data==="limited")){kind="variance";title="Expand representative evidence, then compare controls";message="Strong training fit and a gap that responds to data suggest variance. Prioritize representative coverage, then compare one regularizer at a time using the same validation protocol.";}else if(validation==="weak"){kind="variance";title="Control brittle fit";message="Verify the boundary, then compare capacity reduction, L2 or L1, dropout, valid augmentation, and early stopping individually across repeated seeds.";}else{kind="healthy";title="Protect the validated baseline";message="Do not add complexity merely because controls exist. Stress-test deployment shifts and subgroups, keep the smallest defensible control set, and monitor after release.";}result.className=`strategy-result ${kind}`;result.innerHTML=`<strong>${title}</strong><p>${message}</p>`;});

document.querySelectorAll(".quiz").forEach(quiz=>quiz.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{quiz.querySelectorAll("button").forEach(item=>item.classList.remove("correct","wrong"));const correct=button.dataset.choice===quiz.dataset.answer;button.classList.add(correct?"correct":"wrong");quiz.querySelector(".feedback").textContent=correct?"Correct — the mechanism and evidence are aligned.":"Not quite. Return to the related interaction and identify whether the issue is fit, evidence, or a specific control.";})));
function completionState(){const done=CourseProgress.isComplete(10);document.querySelector("#completeLesson").textContent=done?"Lesson 10 completed ✓":"Mark Lesson 10 complete";document.querySelector("#completionStatus").textContent=done?"Phase 2 is complete. Your model-training specification and evidence card are ready for Engineering Lab A.":"Completion is stored in this browser.";}
document.querySelector("#completeLesson").addEventListener("click",()=>{CourseProgress.complete(10);completionState();});window.addEventListener("course-progress",completionState);

updateFit();renderLearningCurve();updatePenalty();renderDropout();renderAugmentations();updateScale();completionState();
